name: 🔔 ĐẾN HẠN GHI SỐ NƯỚC VÀ THU TIỀN TRỌ
on:
  schedule:
    # Chạy lúc 2:00 AM UTC (tương đương 9:00 AM giờ Việt Nam) vào các ngày 6, 7, 8 hàng tháng
    - cron: '0 2 6,7,8 * *'
  workflow_dispatch: # Cho phép bấm chạy thủ công để test

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Web3Forms Email
        run: |
          curl -X POST https://api.web3forms.com/submit \
          -H "Content-Type: application/json" \
          -d '{
            "access_key": "8587548f-533c-48bd-b674-83a927c9f86b",
            "subject": "🔔 ĐẾN HẠN GHI SỐ NƯỚC VÀ THU TIỀN TRỌ",
            "from_name": "Nhà Trọ Đặng Được ",
            "message": "Hôm nay là ngày ghi số nước và thu tiền trọ. Hãy nhắn tin lấy số nước, đóng tiền điện sau đó vào website nhập liệu data in bill tính tiền"
          }'
