name: 🔔 ĐẾN HẠN THU TIỀN TRỌ TRƯỚC NGÀY 10 HẰNG THÁNG
on:
  schedule:
    # Chạy lúc 2:00 AM UTC (tương đương 9:00 AM giờ Việt Nam) vào các ngày 6, 7, 8, 9 hàng tháng
    - cron: '0 2 6,7,8,9 * *'
  workflow_dispatch: # Cho phép bấm chạy thủ công để test

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Web3Forms Email
        run: |
          curl -X POST https://api.web3forms.com/submit \
          -H "Content-Type: application/json" \
          -d '{
            "access_key": "8587548f-533c-48bd-b674-83a927c9f86b",
            "subject": "🔔 ĐẾN HẠN THU TIỀN TRỌ TRƯỚC NGÀY 10 HẰNG THÁNG",
            "from_name": "Nhà Trọ Đặng Được ",
            "message": "Thu tiền trọ trước DEADLINE NGÀY 10 hằng tháng, nhớ vào cập nhật website và xem lại dữ liệu xem đã đúng chưa"
          }'
